version: '3.8'

services:

  app:
    build:
      context: .
      target: app
    ports:
      - '9000:9000'
    volumes:
      - ./app:/srv/app
  
  database:
    build:
      context: .
      target: database
    ports:
      - "5432:5432"

  nginx:
    build:
      context: .
      target: nginx
    volumes:
      - ./app:/srv/app
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/config/app.conf:/etc/nginx/conf.d/app.conf