version: '3.8'

services:

  database:
    image: mariadb
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} 
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  app:
    ports:
      - '9000:9000'
    volumes:
      - ./app:/srv/app
    environment: 
    - APP_NAME=${APP_NAME}
    - APP_ENV=${APP_ENV}
    - DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASSWORD}@database:3306/${MYSQL_DATABASE}
    - COMPANY_ID=${COMPANY_ID}
    - APP_LOCALE=${APP_LOCALE}
    - DEFAULT_TIMEZONE=${DEFAULT_TIMEZONE}
    depends_on:
      - database

  nginx:
    image: nginx:stable-alpine
    ports:
      - '80:80'
    volumes:
      - ./app:/var/www/app
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - database

volumes:
  db_data:
