<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627064805 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SEQUENCE access_control_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE asset_category_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE customer_group_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE customer_location_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE customer_profile_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE customer_role_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE customer_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE project_activity_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE project_task_activity_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE project_task_tag_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE setting_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_profile_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE SEQUENCE user_type_id_seq INCREMENT BY 1 MINVALUE 1 START 1');
        $this->addSql('CREATE TABLE access_control (id INT NOT NULL, name VARCHAR(64) NOT NULL, reason VARCHAR(255) DEFAULT NULL, path VARCHAR(255) NOT NULL, roles JSON NOT NULL, ips JSON NOT NULL, host VARCHAR(255) DEFAULT NULL, methods JSON NOT NULL, allow BOOLEAN DEFAULT true NOT NULL, sort INT DEFAULT 0 NOT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_access_control_active_sort ON access_control (active, sort)');
        $this->addSql('COMMENT ON COLUMN access_control.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN access_control.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE asset (id SERIAL NOT NULL, model_id INT DEFAULT NULL, name VARCHAR(128) NOT NULL, slug VARCHAR(128) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2AF5A5C989D9B62 ON asset (slug)');
        $this->addSql('CREATE INDEX IDX_2AF5A5C7975B7E7 ON asset (model_id)');
        $this->addSql('CREATE TABLE asset_attachment (id SERIAL NOT NULL, asset_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, type VARCHAR(32) NOT NULL, size INT NOT NULL, path VARCHAR(128) NOT NULL, filename VARCHAR(128) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_BFBE3AE1989D9B62 ON asset_attachment (slug)');
        $this->addSql('CREATE INDEX IDX_BFBE3AE15DA1941 ON asset_attachment (asset_id)');
        $this->addSql('CREATE TABLE asset_brand (id SERIAL NOT NULL, name VARCHAR(128) NOT NULL, slug VARCHAR(128) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8909D71F989D9B62 ON asset_brand (slug)');
        $this->addSql('CREATE TABLE asset_category (id INT NOT NULL, parent_id INT DEFAULT NULL, name VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, slug VARCHAR(128) NOT NULL, lft INT DEFAULT NULL, rgt INT DEFAULT NULL, root INT DEFAULT NULL, lvl INT DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_84270341989D9B62 ON asset_category (slug)');
        $this->addSql('CREATE INDEX IDX_84270341727ACA70 ON asset_category (parent_id)');
        $this->addSql('CREATE TABLE asset_model (id SERIAL NOT NULL, brand_id INT NOT NULL, type_id INT NOT NULL, name VARCHAR(64) NOT NULL, slug VARCHAR(64) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_42CE5C9E989D9B62 ON asset_model (slug)');
        $this->addSql('CREATE INDEX IDX_42CE5C9E44F5D008 ON asset_model (brand_id)');
        $this->addSql('CREATE INDEX IDX_42CE5C9EC54C8C93 ON asset_model (type_id)');
        $this->addSql('CREATE TABLE asset_type (id SERIAL NOT NULL, name VARCHAR(64) NOT NULL, slug VARCHAR(64) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_68BA92E1989D9B62 ON asset_type (slug)');
        $this->addSql('CREATE TABLE auth_assignment (user_id VARCHAR(255) NOT NULL, item_name VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(item_name, user_id))');
        $this->addSql('CREATE INDEX IDX_2EC0490E96133AFD ON auth_assignment (item_name)');
        $this->addSql('CREATE INDEX idx_auth_assignment_user ON auth_assignment (user_id)');
        $this->addSql('COMMENT ON COLUMN auth_assignment.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE auth_item (name VARCHAR(64) NOT NULL, rule_name VARCHAR(64) DEFAULT NULL, type VARCHAR(32) NOT NULL, description TEXT DEFAULT NULL, data JSON DEFAULT \'[]\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(name))');
        $this->addSql('CREATE INDEX IDX_313DC5AADE72171 ON auth_item (rule_name)');
        $this->addSql('CREATE INDEX idx_auth_item_type ON auth_item (type)');
        $this->addSql('COMMENT ON COLUMN auth_item.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN auth_item.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE auth_item_child (parent VARCHAR(64) NOT NULL, child VARCHAR(64) NOT NULL, PRIMARY KEY(parent, child))');
        $this->addSql('CREATE INDEX IDX_1611424D3D8E604F ON auth_item_child (parent)');
        $this->addSql('CREATE INDEX IDX_1611424D22B35429 ON auth_item_child (child)');
        $this->addSql('CREATE TABLE auth_rule (name VARCHAR(64) NOT NULL, service_id VARCHAR(255) DEFAULT NULL, expression TEXT DEFAULT NULL, data JSON DEFAULT \'[]\' NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(name))');
        $this->addSql('COMMENT ON COLUMN auth_rule.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN auth_rule.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE customer (id SERIAL NOT NULL, type_id INT NOT NULL, code VARCHAR(64) NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(255) DEFAULT NULL, unconfirmed_email VARCHAR(255) DEFAULT NULL, registration_ip VARCHAR(64) DEFAULT NULL, active BOOLEAN NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, blocked_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81398E0977153098 ON customer (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81398E09F85E0677 ON customer (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_81398E09E7927C74 ON customer (email)');
        $this->addSql('CREATE INDEX IDX_81398E09C54C8C93 ON customer (type_id)');
        $this->addSql('CREATE TABLE customer_group_assigned (customer_id INT NOT NULL, customer_group_id INT NOT NULL, PRIMARY KEY(customer_id, customer_group_id))');
        $this->addSql('CREATE INDEX IDX_9BC7B42F9395C3F3 ON customer_group_assigned (customer_id)');
        $this->addSql('CREATE INDEX IDX_9BC7B42FD2919A68 ON customer_group_assigned (customer_group_id)');
        $this->addSql('CREATE TABLE customer_role_assigned (customer_id INT NOT NULL, customer_role_id INT NOT NULL, PRIMARY KEY(customer_id, customer_role_id))');
        $this->addSql('CREATE INDEX IDX_452C5AA89395C3F3 ON customer_role_assigned (customer_id)');
        $this->addSql('CREATE INDEX IDX_452C5AA8CADE8612 ON customer_role_assigned (customer_role_id)');
        $this->addSql('CREATE TABLE customer_attachment (id SERIAL NOT NULL, customer_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(32) NOT NULL, size INT NOT NULL, path VARCHAR(128) NOT NULL, filename VARCHAR(128) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_8496DD399395C3F3 ON customer_attachment (customer_id)');
        $this->addSql('CREATE TABLE customer_contact (id SERIAL NOT NULL, customer_location_id INT DEFAULT NULL, firstname VARCHAR(64) NOT NULL, lastname VARCHAR(64) NOT NULL, phone VARCHAR(32) DEFAULT NULL, email VARCHAR(32) DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_50BF42865060A86 ON customer_contact (customer_location_id)');
        $this->addSql('CREATE TABLE customer_group (id INT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, sort SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A3F531FE989D9B62 ON customer_group (slug)');
        $this->addSql('CREATE TABLE customer_location (id INT NOT NULL, customer_id INT NOT NULL, name VARCHAR(128) NOT NULL, address VARCHAR(64) NOT NULL, zipcode VARCHAR(8) NOT NULL, city VARCHAR(64) NOT NULL, country VARCHAR(32) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_725BCAE49395C3F3 ON customer_location (customer_id)');
        $this->addSql('CREATE TABLE customer_location_place (id SERIAL NOT NULL, customer_location_id INT DEFAULT NULL, name VARCHAR(64) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9B2C22225060A86 ON customer_location_place (customer_location_id)');
        $this->addSql('CREATE TABLE customer_location_place_asset (id SERIAL NOT NULL, customer_location_place_id INT NOT NULL, asset_id INT NOT NULL, name VARCHAR(64) NOT NULL, code VARCHAR(64) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6250290EC8E27DE6 ON customer_location_place_asset (customer_location_place_id)');
        $this->addSql('CREATE INDEX IDX_6250290E5DA1941 ON customer_location_place_asset (asset_id)');
        $this->addSql('CREATE TABLE customer_location_place_asset_attachment (id SERIAL NOT NULL, customer_location_place_asset_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(32) NOT NULL, size INT NOT NULL, path VARCHAR(128) NOT NULL, filename VARCHAR(128) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1BB6CC6F43F22647 ON customer_location_place_asset_attachment (customer_location_place_asset_id)');
        $this->addSql('CREATE TABLE customer_profile (id INT NOT NULL, customer_id INT DEFAULT NULL, firstname VARCHAR(255) DEFAULT NULL, lastname VARCHAR(64) NOT NULL, public_email VARCHAR(255) DEFAULT NULL, gravatar_email VARCHAR(255) DEFAULT NULL, gravatar_id VARCHAR(32) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, bio TEXT DEFAULT NULL, timezone VARCHAR(40) DEFAULT NULL, setting TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9D8A0EB19395C3F3 ON customer_profile (customer_id)');
        $this->addSql('COMMENT ON COLUMN customer_profile.setting IS \'settings preferences\'');
        $this->addSql('CREATE TABLE customer_role (id INT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(64) NOT NULL, code VARCHAR(64) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3F82E1D989D9B62 ON customer_role (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3F82E1D77153098 ON customer_role (code)');
        $this->addSql('CREATE TABLE customer_role_hierarchy (parent INT NOT NULL, child INT NOT NULL, PRIMARY KEY(parent, child))');
        $this->addSql('CREATE INDEX IDX_32E3CFB83D8E604F ON customer_role_hierarchy (parent)');
        $this->addSql('CREATE INDEX IDX_32E3CFB822B35429 ON customer_role_hierarchy (child)');
        $this->addSql('CREATE TABLE customer_type (id INT NOT NULL, name VARCHAR(128) DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE notification (id SERIAL NOT NULL, notification_entity_id INT DEFAULT NULL, entity_id INT DEFAULT NULL, message TEXT NOT NULL, status BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_BF5476CA27CC3A02 ON notification (notification_entity_id)');
        $this->addSql('COMMENT ON COLUMN notification.entity_id IS \'NULL with deleted entities\'');
        $this->addSql('CREATE TABLE notification_entity (id SERIAL NOT NULL, name VARCHAR(64) NOT NULL, action VARCHAR(16) NOT NULL, subject VARCHAR(128) NOT NULL, template VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('COMMENT ON COLUMN notification_entity.name IS \'post,comment,task,template\'');
        $this->addSql('CREATE TABLE notification_item (id SERIAL NOT NULL, notification_id INT DEFAULT NULL, recipient_id INT DEFAULT NULL, sender_id INT NOT NULL, status SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A7276E24EF1A9D84 ON notification_item (notification_id)');
        $this->addSql('CREATE INDEX IDX_A7276E24E92F8F78 ON notification_item (recipient_id)');
        $this->addSql('CREATE TABLE project (id SERIAL NOT NULL, type_id INT NOT NULL, code VARCHAR(32) NOT NULL, name VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, datetime_start TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, datetime_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, state VARCHAR(32) NOT NULL, budget NUMERIC(15, 2) DEFAULT NULL, color CHAR(6) DEFAULT NULL, priority SMALLINT NOT NULL, active BOOLEAN NOT NULL, visible BOOLEAN DEFAULT true NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_2FB3D0EEC54C8C93 ON project (type_id)');
        $this->addSql('CREATE TABLE project_activity (id INT NOT NULL, user_id INT NOT NULL, project_id INT NOT NULL, name VARCHAR(128) NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_913A8281A76ED395 ON project_activity (user_id)');
        $this->addSql('CREATE INDEX IDX_913A8281166D1F9C ON project_activity (project_id)');
        $this->addSql('CREATE TABLE project_milestone (id SERIAL NOT NULL, project_id INT NOT NULL, name VARCHAR(32) NOT NULL, expiration_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E90C655166D1F9C ON project_milestone (project_id)');
        $this->addSql('CREATE TABLE project_task (id SERIAL NOT NULL, customer_id INT DEFAULT NULL, customer_location_place_asset_id INT DEFAULT NULL, project_id INT DEFAULT NULL, type_id INT DEFAULT NULL, name VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, state VARCHAR(255) CHECK(state IN (\'requested\', \'rejected\', \'approved\', \'current\', \'dead\', \'completed\', \'on_hold\', \'signed\')) NOT NULL, asset_type VARCHAR(8) DEFAULT \'\'\'N/A\'\'\' NOT NULL, priority VARCHAR(255) CHECK(priority IN (\'low\', \'normal\', \'high\')) NOT NULL, active BOOLEAN NOT NULL, visible VARCHAR(255) NOT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6BEF133D9395C3F3 ON project_task (customer_id)');
        $this->addSql('CREATE INDEX IDX_6BEF133D43F22647 ON project_task (customer_location_place_asset_id)');
        $this->addSql('CREATE INDEX IDX_6BEF133D166D1F9C ON project_task (project_id)');
        $this->addSql('CREATE INDEX IDX_6BEF133DC54C8C93 ON project_task (type_id)');
        $this->addSql('COMMENT ON COLUMN project_task.state IS \'(DC2Type:ProjectTaskStateType)\'');
        $this->addSql('COMMENT ON COLUMN project_task.asset_type IS \'Update with assetType value\'');
        $this->addSql('COMMENT ON COLUMN project_task.priority IS \'(DC2Type:ProjectTaskPriorityType)\'');
        $this->addSql('CREATE TABLE project_task_tag_assigned (project_task_id INT NOT NULL, project_task_tag_id INT NOT NULL, PRIMARY KEY(project_task_id, project_task_tag_id))');
        $this->addSql('CREATE INDEX IDX_C1E9CF531BA80DE3 ON project_task_tag_assigned (project_task_id)');
        $this->addSql('CREATE INDEX IDX_C1E9CF5349B41039 ON project_task_tag_assigned (project_task_tag_id)');
        $this->addSql('CREATE TABLE project_task_user_assigned (project_task_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(project_task_id, user_id))');
        $this->addSql('CREATE INDEX IDX_18521BAA1BA80DE3 ON project_task_user_assigned (project_task_id)');
        $this->addSql('CREATE INDEX IDX_18521BAAA76ED395 ON project_task_user_assigned (user_id)');
        $this->addSql('CREATE TABLE project_task_activity (id INT NOT NULL, user_id INT NOT NULL, project_task_id INT NOT NULL, name VARCHAR(128) NOT NULL, datetime TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_38257410A76ED395 ON project_task_activity (user_id)');
        $this->addSql('CREATE INDEX IDX_382574101BA80DE3 ON project_task_activity (project_task_id)');
        $this->addSql('CREATE TABLE project_task_attachment (id SERIAL NOT NULL, user_id INT DEFAULT NULL, project_task_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(32) DEFAULT \'\'\'image\'\'\' NOT NULL, size INT NOT NULL, path VARCHAR(128) NOT NULL, filename VARCHAR(128) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5D7DE7E4A76ED395 ON project_task_attachment (user_id)');
        $this->addSql('CREATE INDEX IDX_5D7DE7E41BA80DE3 ON project_task_attachment (project_task_id)');
        $this->addSql('CREATE TABLE project_task_item (id SERIAL NOT NULL, project_task_id INT NOT NULL, name VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, difficulty SMALLINT NOT NULL, value CHAR(1) DEFAULT NULL, datetime_start TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, datetime_end TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_7D94F4B21BA80DE3 ON project_task_item (project_task_id)');
        $this->addSql('CREATE TABLE project_task_item_assigned (id SERIAL NOT NULL, user_id INT DEFAULT NULL, project_task_item_id INT DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_94D23761A76ED395 ON project_task_item_assigned (user_id)');
        $this->addSql('CREATE INDEX IDX_94D2376127299CD7 ON project_task_item_assigned (project_task_item_id)');
        $this->addSql('CREATE TABLE project_task_item_template (id SERIAL NOT NULL, task_template_id INT NOT NULL, task_type_id INT NOT NULL, name VARCHAR(255) NOT NULL, sort INT NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_828E47843AFA28A ON project_task_item_template (task_template_id)');
        $this->addSql('CREATE INDEX IDX_828E478DAADA679 ON project_task_item_template (task_type_id)');
        $this->addSql('CREATE TABLE project_task_milestone (id SERIAL NOT NULL, project_milestone_id INT NOT NULL, project_task_id INT NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D9317A716199CAB9 ON project_task_milestone (project_milestone_id)');
        $this->addSql('CREATE INDEX IDX_D9317A711BA80DE3 ON project_task_milestone (project_task_id)');
        $this->addSql('CREATE TABLE project_task_tag (id INT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE project_task_template (id SERIAL NOT NULL, name VARCHAR(128) NOT NULL, description TEXT DEFAULT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE project_task_type (id SERIAL NOT NULL, name VARCHAR(128) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE project_type (id SERIAL NOT NULL, name VARCHAR(128) NOT NULL, active BOOLEAN NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE setting (id INT NOT NULL, tenant_id INT NOT NULL, name VARCHAR(255) NOT NULL, value TEXT NOT NULL, type VARCHAR(20) DEFAULT \'string\' NOT NULL, active BOOLEAN DEFAULT true NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX idx_setting_tenant_active ON setting (tenant_id, active)');
        $this->addSql('CREATE UNIQUE INDEX uniq_setting_tenant_name ON setting (tenant_id, name)');
        $this->addSql('COMMENT ON COLUMN setting.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN setting.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE "user" (id SERIAL NOT NULL, type_id INT NOT NULL, code VARCHAR(64) NOT NULL, username VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL, password VARCHAR(60) NOT NULL, confirmed_at INT DEFAULT NULL, unconfirmed_email VARCHAR(255) DEFAULT NULL, blocked_at INT DEFAULT NULL, registration_ip VARCHAR(45) DEFAULT NULL, active BOOLEAN NOT NULL, deleted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_login_at INT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D64977153098 ON "user" (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE INDEX IDX_8D93D649C54C8C93 ON "user" (type_id)');
        $this->addSql('CREATE TABLE user_role_assigned (user_id INT NOT NULL, user_role_id INT NOT NULL, PRIMARY KEY(user_id, user_role_id))');
        $this->addSql('CREATE INDEX IDX_CFC787FBA76ED395 ON user_role_assigned (user_id)');
        $this->addSql('CREATE INDEX IDX_CFC787FB8E0E3CA6 ON user_role_assigned (user_role_id)');
        $this->addSql('CREATE TABLE user_group_assigned (user_id INT NOT NULL, user_group_id INT NOT NULL, PRIMARY KEY(user_id, user_group_id))');
        $this->addSql('CREATE INDEX IDX_692F5FBCA76ED395 ON user_group_assigned (user_id)');
        $this->addSql('CREATE INDEX IDX_692F5FBC1ED93D47 ON user_group_assigned (user_group_id)');
        $this->addSql('CREATE TABLE user_customer_assigned (user_id INT NOT NULL, customer_id INT NOT NULL, PRIMARY KEY(user_id, customer_id))');
        $this->addSql('CREATE INDEX IDX_DF40349EA76ED395 ON user_customer_assigned (user_id)');
        $this->addSql('CREATE INDEX IDX_DF40349E9395C3F3 ON user_customer_assigned (customer_id)');
        $this->addSql('CREATE TABLE user_attachment (id SERIAL NOT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, type VARCHAR(32) NOT NULL, size INT NOT NULL, path VARCHAR(128) NOT NULL, filename VARCHAR(128) NOT NULL, active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_DE381F57A76ED395 ON user_attachment (user_id)');
        $this->addSql('CREATE TABLE user_group (id SERIAL NOT NULL, name VARCHAR(64) NOT NULL, slug VARCHAR(64) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE user_profile (id INT NOT NULL, user_id INT DEFAULT NULL, firstname VARCHAR(255) DEFAULT NULL, lastname VARCHAR(64) DEFAULT NULL, public_email VARCHAR(255) DEFAULT NULL, gravatar_email VARCHAR(255) DEFAULT NULL, gravatar_id VARCHAR(32) DEFAULT NULL, location VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, bio TEXT DEFAULT NULL, timezone VARCHAR(40) DEFAULT NULL, setting TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D95AB405A76ED395 ON user_profile (user_id)');
        $this->addSql('COMMENT ON COLUMN user_profile.setting IS \'settings like notifications\'');
        $this->addSql('CREATE TABLE user_role (id SERIAL NOT NULL, slug VARCHAR(64) NOT NULL, name VARCHAR(64) NOT NULL, code VARCHAR(64) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DE8C6A3989D9B62 ON user_role (slug)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DE8C6A377153098 ON user_role (code)');
        $this->addSql('CREATE TABLE user_role_hierarchy (child INT NOT NULL, parent INT NOT NULL, PRIMARY KEY(child, parent))');
        $this->addSql('CREATE INDEX IDX_C00B242B22B35429 ON user_role_hierarchy (child)');
        $this->addSql('CREATE INDEX IDX_C00B242B3D8E604F ON user_role_hierarchy (parent)');
        $this->addSql('CREATE TABLE user_type (id INT NOT NULL, name VARCHAR(128) NOT NULL, slug VARCHAR(64) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE website (id SERIAL NOT NULL, name VARCHAR(32) NOT NULL, code VARCHAR(32) NOT NULL, active BOOLEAN NOT NULL, default_group_id INT NOT NULL, sort SMALLINT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_476F5DE777153098 ON website (code)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE asset ADD CONSTRAINT FK_2AF5A5C7975B7E7 FOREIGN KEY (model_id) REFERENCES asset_model (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE asset_attachment ADD CONSTRAINT FK_BFBE3AE15DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE asset_category ADD CONSTRAINT FK_84270341727ACA70 FOREIGN KEY (parent_id) REFERENCES asset_category (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE asset_model ADD CONSTRAINT FK_42CE5C9E44F5D008 FOREIGN KEY (brand_id) REFERENCES asset_brand (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE asset_model ADD CONSTRAINT FK_42CE5C9EC54C8C93 FOREIGN KEY (type_id) REFERENCES asset_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auth_assignment ADD CONSTRAINT FK_2EC0490E96133AFD FOREIGN KEY (item_name) REFERENCES auth_item (name) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auth_item ADD CONSTRAINT FK_313DC5AADE72171 FOREIGN KEY (rule_name) REFERENCES auth_rule (name) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auth_item_child ADD CONSTRAINT FK_1611424D3D8E604F FOREIGN KEY (parent) REFERENCES auth_item (name) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE auth_item_child ADD CONSTRAINT FK_1611424D22B35429 FOREIGN KEY (child) REFERENCES auth_item (name) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer ADD CONSTRAINT FK_81398E09C54C8C93 FOREIGN KEY (type_id) REFERENCES customer_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_group_assigned ADD CONSTRAINT FK_9BC7B42F9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_group_assigned ADD CONSTRAINT FK_9BC7B42FD2919A68 FOREIGN KEY (customer_group_id) REFERENCES customer_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_role_assigned ADD CONSTRAINT FK_452C5AA89395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_role_assigned ADD CONSTRAINT FK_452C5AA8CADE8612 FOREIGN KEY (customer_role_id) REFERENCES customer_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_attachment ADD CONSTRAINT FK_8496DD399395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_contact ADD CONSTRAINT FK_50BF42865060A86 FOREIGN KEY (customer_location_id) REFERENCES customer_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_location ADD CONSTRAINT FK_725BCAE49395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_location_place ADD CONSTRAINT FK_9B2C22225060A86 FOREIGN KEY (customer_location_id) REFERENCES customer_location (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_location_place_asset ADD CONSTRAINT FK_6250290EC8E27DE6 FOREIGN KEY (customer_location_place_id) REFERENCES customer_location_place (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_location_place_asset ADD CONSTRAINT FK_6250290E5DA1941 FOREIGN KEY (asset_id) REFERENCES asset (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_location_place_asset_attachment ADD CONSTRAINT FK_1BB6CC6F43F22647 FOREIGN KEY (customer_location_place_asset_id) REFERENCES customer_location_place_asset (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_profile ADD CONSTRAINT FK_9D8A0EB19395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_role_hierarchy ADD CONSTRAINT FK_32E3CFB83D8E604F FOREIGN KEY (parent) REFERENCES customer_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE customer_role_hierarchy ADD CONSTRAINT FK_32E3CFB822B35429 FOREIGN KEY (child) REFERENCES customer_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification ADD CONSTRAINT FK_BF5476CA27CC3A02 FOREIGN KEY (notification_entity_id) REFERENCES notification_entity (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_item ADD CONSTRAINT FK_A7276E24EF1A9D84 FOREIGN KEY (notification_id) REFERENCES notification (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE notification_item ADD CONSTRAINT FK_A7276E24E92F8F78 FOREIGN KEY (recipient_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project ADD CONSTRAINT FK_2FB3D0EEC54C8C93 FOREIGN KEY (type_id) REFERENCES project_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_activity ADD CONSTRAINT FK_913A8281A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_activity ADD CONSTRAINT FK_913A8281166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_milestone ADD CONSTRAINT FK_5E90C655166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF133D9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF133D43F22647 FOREIGN KEY (customer_location_place_asset_id) REFERENCES customer_location_place_asset (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF133D166D1F9C FOREIGN KEY (project_id) REFERENCES project (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task ADD CONSTRAINT FK_6BEF133DC54C8C93 FOREIGN KEY (type_id) REFERENCES project_task_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_tag_assigned ADD CONSTRAINT FK_C1E9CF531BA80DE3 FOREIGN KEY (project_task_id) REFERENCES project_task (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_tag_assigned ADD CONSTRAINT FK_C1E9CF5349B41039 FOREIGN KEY (project_task_tag_id) REFERENCES project_task_tag (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_user_assigned ADD CONSTRAINT FK_18521BAA1BA80DE3 FOREIGN KEY (project_task_id) REFERENCES project_task (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_user_assigned ADD CONSTRAINT FK_18521BAAA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_activity ADD CONSTRAINT FK_38257410A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_activity ADD CONSTRAINT FK_382574101BA80DE3 FOREIGN KEY (project_task_id) REFERENCES project_task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_attachment ADD CONSTRAINT FK_5D7DE7E4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_attachment ADD CONSTRAINT FK_5D7DE7E41BA80DE3 FOREIGN KEY (project_task_id) REFERENCES project_task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_item ADD CONSTRAINT FK_7D94F4B21BA80DE3 FOREIGN KEY (project_task_id) REFERENCES project_task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_item_assigned ADD CONSTRAINT FK_94D23761A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_item_assigned ADD CONSTRAINT FK_94D2376127299CD7 FOREIGN KEY (project_task_item_id) REFERENCES project_task_item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_item_template ADD CONSTRAINT FK_828E47843AFA28A FOREIGN KEY (task_template_id) REFERENCES project_task_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_item_template ADD CONSTRAINT FK_828E478DAADA679 FOREIGN KEY (task_type_id) REFERENCES project_task_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_milestone ADD CONSTRAINT FK_D9317A716199CAB9 FOREIGN KEY (project_milestone_id) REFERENCES project_milestone (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE project_task_milestone ADD CONSTRAINT FK_D9317A711BA80DE3 FOREIGN KEY (project_task_id) REFERENCES project_task (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649C54C8C93 FOREIGN KEY (type_id) REFERENCES user_type (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_role_assigned ADD CONSTRAINT FK_CFC787FBA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_role_assigned ADD CONSTRAINT FK_CFC787FB8E0E3CA6 FOREIGN KEY (user_role_id) REFERENCES user_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_group_assigned ADD CONSTRAINT FK_692F5FBCA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_group_assigned ADD CONSTRAINT FK_692F5FBC1ED93D47 FOREIGN KEY (user_group_id) REFERENCES user_group (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_customer_assigned ADD CONSTRAINT FK_DF40349EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_customer_assigned ADD CONSTRAINT FK_DF40349E9395C3F3 FOREIGN KEY (customer_id) REFERENCES customer (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_attachment ADD CONSTRAINT FK_DE381F57A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_profile ADD CONSTRAINT FK_D95AB405A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_role_hierarchy ADD CONSTRAINT FK_C00B242B22B35429 FOREIGN KEY (child) REFERENCES user_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE user_role_hierarchy ADD CONSTRAINT FK_C00B242B3D8E604F FOREIGN KEY (parent) REFERENCES user_role (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP SEQUENCE access_control_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE asset_category_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE customer_group_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE customer_location_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE customer_profile_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE customer_role_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE customer_type_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE project_activity_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE project_task_activity_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE project_task_tag_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE setting_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_profile_id_seq CASCADE');
        $this->addSql('DROP SEQUENCE user_type_id_seq CASCADE');
        $this->addSql('ALTER TABLE asset DROP CONSTRAINT FK_2AF5A5C7975B7E7');
        $this->addSql('ALTER TABLE asset_attachment DROP CONSTRAINT FK_BFBE3AE15DA1941');
        $this->addSql('ALTER TABLE asset_category DROP CONSTRAINT FK_84270341727ACA70');
        $this->addSql('ALTER TABLE asset_model DROP CONSTRAINT FK_42CE5C9E44F5D008');
        $this->addSql('ALTER TABLE asset_model DROP CONSTRAINT FK_42CE5C9EC54C8C93');
        $this->addSql('ALTER TABLE auth_assignment DROP CONSTRAINT FK_2EC0490E96133AFD');
        $this->addSql('ALTER TABLE auth_item DROP CONSTRAINT FK_313DC5AADE72171');
        $this->addSql('ALTER TABLE auth_item_child DROP CONSTRAINT FK_1611424D3D8E604F');
        $this->addSql('ALTER TABLE auth_item_child DROP CONSTRAINT FK_1611424D22B35429');
        $this->addSql('ALTER TABLE customer DROP CONSTRAINT FK_81398E09C54C8C93');
        $this->addSql('ALTER TABLE customer_group_assigned DROP CONSTRAINT FK_9BC7B42F9395C3F3');
        $this->addSql('ALTER TABLE customer_group_assigned DROP CONSTRAINT FK_9BC7B42FD2919A68');
        $this->addSql('ALTER TABLE customer_role_assigned DROP CONSTRAINT FK_452C5AA89395C3F3');
        $this->addSql('ALTER TABLE customer_role_assigned DROP CONSTRAINT FK_452C5AA8CADE8612');
        $this->addSql('ALTER TABLE customer_attachment DROP CONSTRAINT FK_8496DD399395C3F3');
        $this->addSql('ALTER TABLE customer_contact DROP CONSTRAINT FK_50BF42865060A86');
        $this->addSql('ALTER TABLE customer_location DROP CONSTRAINT FK_725BCAE49395C3F3');
        $this->addSql('ALTER TABLE customer_location_place DROP CONSTRAINT FK_9B2C22225060A86');
        $this->addSql('ALTER TABLE customer_location_place_asset DROP CONSTRAINT FK_6250290EC8E27DE6');
        $this->addSql('ALTER TABLE customer_location_place_asset DROP CONSTRAINT FK_6250290E5DA1941');
        $this->addSql('ALTER TABLE customer_location_place_asset_attachment DROP CONSTRAINT FK_1BB6CC6F43F22647');
        $this->addSql('ALTER TABLE customer_profile DROP CONSTRAINT FK_9D8A0EB19395C3F3');
        $this->addSql('ALTER TABLE customer_role_hierarchy DROP CONSTRAINT FK_32E3CFB83D8E604F');
        $this->addSql('ALTER TABLE customer_role_hierarchy DROP CONSTRAINT FK_32E3CFB822B35429');
        $this->addSql('ALTER TABLE notification DROP CONSTRAINT FK_BF5476CA27CC3A02');
        $this->addSql('ALTER TABLE notification_item DROP CONSTRAINT FK_A7276E24EF1A9D84');
        $this->addSql('ALTER TABLE notification_item DROP CONSTRAINT FK_A7276E24E92F8F78');
        $this->addSql('ALTER TABLE project DROP CONSTRAINT FK_2FB3D0EEC54C8C93');
        $this->addSql('ALTER TABLE project_activity DROP CONSTRAINT FK_913A8281A76ED395');
        $this->addSql('ALTER TABLE project_activity DROP CONSTRAINT FK_913A8281166D1F9C');
        $this->addSql('ALTER TABLE project_milestone DROP CONSTRAINT FK_5E90C655166D1F9C');
        $this->addSql('ALTER TABLE project_task DROP CONSTRAINT FK_6BEF133D9395C3F3');
        $this->addSql('ALTER TABLE project_task DROP CONSTRAINT FK_6BEF133D43F22647');
        $this->addSql('ALTER TABLE project_task DROP CONSTRAINT FK_6BEF133D166D1F9C');
        $this->addSql('ALTER TABLE project_task DROP CONSTRAINT FK_6BEF133DC54C8C93');
        $this->addSql('ALTER TABLE project_task_tag_assigned DROP CONSTRAINT FK_C1E9CF531BA80DE3');
        $this->addSql('ALTER TABLE project_task_tag_assigned DROP CONSTRAINT FK_C1E9CF5349B41039');
        $this->addSql('ALTER TABLE project_task_user_assigned DROP CONSTRAINT FK_18521BAA1BA80DE3');
        $this->addSql('ALTER TABLE project_task_user_assigned DROP CONSTRAINT FK_18521BAAA76ED395');
        $this->addSql('ALTER TABLE project_task_activity DROP CONSTRAINT FK_38257410A76ED395');
        $this->addSql('ALTER TABLE project_task_activity DROP CONSTRAINT FK_382574101BA80DE3');
        $this->addSql('ALTER TABLE project_task_attachment DROP CONSTRAINT FK_5D7DE7E4A76ED395');
        $this->addSql('ALTER TABLE project_task_attachment DROP CONSTRAINT FK_5D7DE7E41BA80DE3');
        $this->addSql('ALTER TABLE project_task_item DROP CONSTRAINT FK_7D94F4B21BA80DE3');
        $this->addSql('ALTER TABLE project_task_item_assigned DROP CONSTRAINT FK_94D23761A76ED395');
        $this->addSql('ALTER TABLE project_task_item_assigned DROP CONSTRAINT FK_94D2376127299CD7');
        $this->addSql('ALTER TABLE project_task_item_template DROP CONSTRAINT FK_828E47843AFA28A');
        $this->addSql('ALTER TABLE project_task_item_template DROP CONSTRAINT FK_828E478DAADA679');
        $this->addSql('ALTER TABLE project_task_milestone DROP CONSTRAINT FK_D9317A716199CAB9');
        $this->addSql('ALTER TABLE project_task_milestone DROP CONSTRAINT FK_D9317A711BA80DE3');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649C54C8C93');
        $this->addSql('ALTER TABLE user_role_assigned DROP CONSTRAINT FK_CFC787FBA76ED395');
        $this->addSql('ALTER TABLE user_role_assigned DROP CONSTRAINT FK_CFC787FB8E0E3CA6');
        $this->addSql('ALTER TABLE user_group_assigned DROP CONSTRAINT FK_692F5FBCA76ED395');
        $this->addSql('ALTER TABLE user_group_assigned DROP CONSTRAINT FK_692F5FBC1ED93D47');
        $this->addSql('ALTER TABLE user_customer_assigned DROP CONSTRAINT FK_DF40349EA76ED395');
        $this->addSql('ALTER TABLE user_customer_assigned DROP CONSTRAINT FK_DF40349E9395C3F3');
        $this->addSql('ALTER TABLE user_attachment DROP CONSTRAINT FK_DE381F57A76ED395');
        $this->addSql('ALTER TABLE user_profile DROP CONSTRAINT FK_D95AB405A76ED395');
        $this->addSql('ALTER TABLE user_role_hierarchy DROP CONSTRAINT FK_C00B242B22B35429');
        $this->addSql('ALTER TABLE user_role_hierarchy DROP CONSTRAINT FK_C00B242B3D8E604F');
        $this->addSql('DROP TABLE access_control');
        $this->addSql('DROP TABLE asset');
        $this->addSql('DROP TABLE asset_attachment');
        $this->addSql('DROP TABLE asset_brand');
        $this->addSql('DROP TABLE asset_category');
        $this->addSql('DROP TABLE asset_model');
        $this->addSql('DROP TABLE asset_type');
        $this->addSql('DROP TABLE auth_assignment');
        $this->addSql('DROP TABLE auth_item');
        $this->addSql('DROP TABLE auth_item_child');
        $this->addSql('DROP TABLE auth_rule');
        $this->addSql('DROP TABLE customer');
        $this->addSql('DROP TABLE customer_group_assigned');
        $this->addSql('DROP TABLE customer_role_assigned');
        $this->addSql('DROP TABLE customer_attachment');
        $this->addSql('DROP TABLE customer_contact');
        $this->addSql('DROP TABLE customer_group');
        $this->addSql('DROP TABLE customer_location');
        $this->addSql('DROP TABLE customer_location_place');
        $this->addSql('DROP TABLE customer_location_place_asset');
        $this->addSql('DROP TABLE customer_location_place_asset_attachment');
        $this->addSql('DROP TABLE customer_profile');
        $this->addSql('DROP TABLE customer_role');
        $this->addSql('DROP TABLE customer_role_hierarchy');
        $this->addSql('DROP TABLE customer_type');
        $this->addSql('DROP TABLE notification');
        $this->addSql('DROP TABLE notification_entity');
        $this->addSql('DROP TABLE notification_item');
        $this->addSql('DROP TABLE project');
        $this->addSql('DROP TABLE project_activity');
        $this->addSql('DROP TABLE project_milestone');
        $this->addSql('DROP TABLE project_task');
        $this->addSql('DROP TABLE project_task_tag_assigned');
        $this->addSql('DROP TABLE project_task_user_assigned');
        $this->addSql('DROP TABLE project_task_activity');
        $this->addSql('DROP TABLE project_task_attachment');
        $this->addSql('DROP TABLE project_task_item');
        $this->addSql('DROP TABLE project_task_item_assigned');
        $this->addSql('DROP TABLE project_task_item_template');
        $this->addSql('DROP TABLE project_task_milestone');
        $this->addSql('DROP TABLE project_task_tag');
        $this->addSql('DROP TABLE project_task_template');
        $this->addSql('DROP TABLE project_task_type');
        $this->addSql('DROP TABLE project_type');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE user_role_assigned');
        $this->addSql('DROP TABLE user_group_assigned');
        $this->addSql('DROP TABLE user_customer_assigned');
        $this->addSql('DROP TABLE user_attachment');
        $this->addSql('DROP TABLE user_group');
        $this->addSql('DROP TABLE user_profile');
        $this->addSql('DROP TABLE user_role');
        $this->addSql('DROP TABLE user_role_hierarchy');
        $this->addSql('DROP TABLE user_type');
        $this->addSql('DROP TABLE website');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
