<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Migra la tabella access_control allo schema dell'entità del bundle
 * fedale/access-control-bundle (Fedale\AccessControlBundle\Bridge\Doctrine\Entity\AccessControlEntity):
 * roles/ips/methods diventano JSON, allow diventa boolean, nuova colonna reason,
 * timestamp senza time zone e indici rinominati in idx_access_control_*.
 *
 * La tabella conteneva solo la regola demo (rimossa dalle fixtures), quindi
 * viene ricreata da zero per allinearsi esattamente ai metadata Doctrine.
 */
final class Version20260618120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Allinea access_control allo schema di fedale/access-control-bundle';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE access_control');
        $this->addSql('CREATE TABLE access_control (
            id SERIAL NOT NULL,
            name VARCHAR(64) NOT NULL,
            reason VARCHAR(255) DEFAULT NULL,
            path VARCHAR(255) NOT NULL,
            roles JSON NOT NULL,
            ips JSON NOT NULL,
            host VARCHAR(255) DEFAULT NULL,
            methods JSON NOT NULL,
            allow BOOLEAN DEFAULT true NOT NULL,
            sort INT DEFAULT 0 NOT NULL,
            active BOOLEAN DEFAULT true NOT NULL,
            created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX idx_access_control_name ON access_control (name)');
        $this->addSql('CREATE INDEX idx_access_control_path ON access_control (path)');
        $this->addSql('CREATE INDEX idx_access_control_host ON access_control (host)');
        $this->addSql('CREATE INDEX idx_access_control_allow ON access_control (allow)');
        $this->addSql('CREATE INDEX idx_access_control_sort ON access_control (sort)');
        $this->addSql('CREATE INDEX idx_access_control_active ON access_control (active)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE access_control');
        $this->addSql('CREATE TABLE access_control (
            id SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
            name VARCHAR(64) NOT NULL,
            path VARCHAR(255) NOT NULL,
            roles VARCHAR(255) DEFAULT NULL,
            ips VARCHAR(255) DEFAULT NULL,
            host VARCHAR(255) DEFAULT NULL,
            methods VARCHAR(255) DEFAULT NULL,
            allow SMALLINT DEFAULT 1 NOT NULL,
            sort SMALLINT DEFAULT 0 NOT NULL,
            active BOOLEAN DEFAULT true NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
            PRIMARY KEY(id)
        )');
        $this->addSql('CREATE INDEX access_control_name_idx ON access_control (name)');
        $this->addSql('CREATE INDEX access_control_path_idx ON access_control (path)');
        $this->addSql('CREATE INDEX access_control_host_idx ON access_control (host)');
        $this->addSql('CREATE INDEX access_control_allow_idx ON access_control (allow)');
        $this->addSql('CREATE INDEX access_control_sort_idx ON access_control (sort)');
        $this->addSql('CREATE INDEX access_control_active_idx ON access_control (active)');
    }
}
