services:
  App\Grid\Source\Entity:
    public: true
    arguments: 
      - '@doctrine.orm.default_entity_manager'
  App\Grid\GridView:
    arguments:
      - '@doctrine.orm.default_entity_manager'
      - '@doctrine.orm.default_entity_manager'