fedale_gridview:
  defaults:
    options:
      emptyText: "No records found"
      useTurbo: true
      showHeader: true
      showFooter: true
    attributes: {}
#     class: "table table-striped"
#     container:
#       class: "table-responsive"

  gridviews: {}
#   customer_list:
#     options:
#       globalSearch: ["c.code", "c.email"]
#     attributes:
#       class: "table table-dark"
#       row:
#         class: "custom-row"
