fedale_gridview:
  defaults:
    options:
      emptyText: "No records found"
      useTurbo: true
      showThead: true
      showTfoot: true
      maxQueryLength: 8000
      # layout:
      #   gridview: "{header} {table} {footer}"
      #   header:   "{globalSearch}"
      #   table:    "{thead} {filter} {tbody} {tfoot}"
      #   footer:   "{pagination}"
    attributes: {}
#     class: "table table-striped"
#     container:
#       class: "table-responsive"

  gridviews: {}
#   customer_list:
#     options:
#       globalSearch: ["c.code", "c.email"]
#       layout:
#         table: "{tbody}"                    # solo body, niente thead/filter/tfoot
#         footer: "{pagination}"
#       templates:
#         header: "@App/gridview/custom_header.html.twig"
#     attributes:
#       class: "table table-dark"
#       row:
#         class: "custom-row"
